### ISSUE TITLE
basic_classification_stats.py  file is gone?

### ISSUE THREAD

**Issue by antoinecourtin** [zooniverse/Data-digging#38]
Hy,
In the readme,.md you specify the `basic_classification_stats.py` file but unless I'm mistaken, I don't find this script in the list of script examples
https://github.com/zooniverse/Data-digging/tree/master/example_scripts

Thanks in advance and sorry if the question is silly ;)

**Comment by camallen** [comment]
Not a silly question at all @antoinecourtin - seems this should refer to `basic_classification_processing.py` in https://github.com/zooniverse/Data-digging/blob/master/example_scripts/basic_classification_processing.py instead. 

Try that command to see if it provides the same functionality as reported in the readme. If so i'll update the docs to point to it. Thanks for reporting this :+1:

**Comment by antoinecourtin** [comment]
Thanks for the answer.
still in the readme, it says links to Jupyter notebooks but the basic_classification_processing.py script doesn't seem to match? 
thank you in advance,

**Comment by camallen** [comment]
I'm not sure i follow but I haven't updated the readme yet. I was hoping you would try the renamed file out to ensure it works for you and does what the docs suggest it should, e.g. 
`python example_scripts/basic_classification_processing.py`

In case you didn't see, I've issued a pull request to update the docs, https://github.com/zooniverse/Data-digging/pull/39/files

**Comment by vrooje** [comment]
Oops! Apologies, I changed the name from `stats` to `processing` because the scripts do more than produce stats and I've found the file cleanup aspects to be the most useful parts of it... but I forgot to change the readme. Well spotted!
