### ISSUE TITLE
Generalized Panoptes Reduction Script

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/Data-digging#7]
This repo contains multiple examples of individually-customized, project-specific scripts that all perform a similar transformation: 
INPUT = the Panoptes *classifications* export CSV (with JSON-encoded annotations info)
OUTPUT = a flat CSV file containing extracted marking/classification data in a flat, non-hierarchical format

Using the information provided in the *workflow* export CSV, one should be able to write a generalized reduction script that could replace many project-specific scripts.

**Comment by vrooje** [comment]
Have added [get_workflow_info.py](https://github.com/zooniverse/Data-digging/blob/master/example_scripts/get_workflow_info.py) for a start on this.

Next up would be a basic aggregation of question tasks that takes the info from the workflow, ignores all but question tasks, and aggregates.

For marking tasks, the [extract_markings.py](https://github.com/zooniverse/Data-digging/blob/master/example_scripts/flying_hi/extract_markings.py) script in the flying-hi directory has a better example of a script that extracts marks from multiple marking tasks and exports them to  individual files (one per tool), ready for a clustering algorithm. It's not generalized, though (e.g. I didn't try to extract polygons).

**Comment by camallen** [comment]
Linking in the custom code that we are using for caesar via https://github.com/zooniverse/aggregation-for-caesar#offline-use and the docs at https://aggregation-caesar.zooniverse.org/docs

That code can currently handle most tools we support via extractors (pull data from each classification and store it in a csv file) and reducers (aggregate the extracted data to a final result csv file).

**Comment by lcjohnso** [comment]
Closing -- makes sense to point people to Aggregations code rather than create a parallel solution here.
